function(AbsToRelPath OUT_VAR BASE_DIR)
    set(result)
    foreach(file IN LISTS ARGN)
        if (IS_ABSOLUTE "${file}")
            file(RELATIVE_PATH rel "${BASE_DIR}" "${file}")
        else()
            set(rel "${file}")
        endif()
        list(APPEND result "${rel}")
    endforeach()
    set(${OUT_VAR} "${result}" PARENT_SCOPE)
endfunction()